import { AmazonPay } from "./front/CFW/Compatibility/AmazonPay";
import { BlueCheck } from "./front/CFW/Compatibility/BlueCheck";
import { Braintree } from "./front/CFW/Compatibility/Braintree";
import { BraintreeForWooCommerce } from "./front/CFW/Compatibility/BraintreeForWooCommerce";
import { CO2OK } from "./front/CFW/Compatibility/CO2OK";
import { EUVatNumber } from "./front/CFW/Compatibility/EUVatNumber";
import { InpsydePayPalPlus } from "./front/CFW/Compatibility/InpsydePayPalPlus";
import { KlarnaCheckout } from "./front/CFW/Compatibility/KlarnaCheckout";
import { KlarnaPayments } from "./front/CFW/Compatibility/KlarnaPayments";
import { MondialRelay } from "./front/CFW/Compatibility/MondialRelay";
import { NLPostcodeChecker } from "./front/CFW/Compatibility/NLPostcodeChecker";
import { OrderDeliveryDate } from "./front/CFW/Compatibility/OrderDeliveryDate";
import { PayPalCheckout } from "./front/CFW/Compatibility/PayPalCheckout";
import { PayPalForWooCommerce } from "./front/CFW/Compatibility/PayPalForWooCommerce";
import { PostNL } from "./front/CFW/Compatibility/PostNL";
import { SendCloud } from "./front/CFW/Compatibility/SendCloud";
import { ShipMondo } from "./front/CFW/Compatibility/ShipMondo";
import { Square } from "./front/CFW/Compatibility/Square";
import { Square1x } from "./front/CFW/Compatibility/Square1x";
import { SquareRecurring } from "./front/CFW/Compatibility/SquareRecurring";
import { Stripe } from "./front/CFW/Compatibility/Stripe";
import { WooCommerceAddressValidation } from "./front/CFW/Compatibility/WooCommerceAddressValidation";
import { WooCommerceGermanized } from "./front/CFW/Compatibility/WooCommerceGermanized";
import { WooFunnelsOrderBumps } from "./front/CFW/Compatibility/WooFunnelsOrderBumps";
import { WooSquarePro } from "./front/CFW/Compatibility/WooSquarePro";

export let CompatibilityClasses: any = {};

CompatibilityClasses.AmazonPay = AmazonPay;
CompatibilityClasses.BlueCheck = BlueCheck;
CompatibilityClasses.Braintree = Braintree;
CompatibilityClasses.BraintreeForWooCommerce = BraintreeForWooCommerce;
CompatibilityClasses.CO2OK = CO2OK;
CompatibilityClasses.EUVatNumber = EUVatNumber;
CompatibilityClasses.InpsydePayPalPlus = InpsydePayPalPlus;
CompatibilityClasses.KlarnaCheckout = KlarnaCheckout;
CompatibilityClasses.KlarnaPayments = KlarnaPayments;
CompatibilityClasses.MondialRelay = MondialRelay;
CompatibilityClasses.NLPostcodeChecker = NLPostcodeChecker;
CompatibilityClasses.OrderDeliveryDate = OrderDeliveryDate;
CompatibilityClasses.PayPalCheckout = PayPalCheckout;
CompatibilityClasses.PayPalForWooCommerce = PayPalForWooCommerce;
CompatibilityClasses.PostNL = PostNL;
CompatibilityClasses.SendCloud = SendCloud;
CompatibilityClasses.ShipMondo = ShipMondo;
CompatibilityClasses.Square = Square;
CompatibilityClasses.Square1x = Square1x;
CompatibilityClasses.SquareRecurring = SquareRecurring;
CompatibilityClasses.Stripe = Stripe;
CompatibilityClasses.WooCommerceAddressValidation = WooCommerceAddressValidation;
CompatibilityClasses.WooCommerceGermanized = WooCommerceGermanized;
CompatibilityClasses.WooFunnelsOrderBumps = WooFunnelsOrderBumps;
CompatibilityClasses.WooSquarePro = WooSquarePro;